namespace Car_Rental.Common.Error;

public enum ErrorTypes
{
    VEHICLE_DUPLICATE_REGNO,
    VEHICLE_ALREADY_BOOKED,
    VEHICLE_RENTING_DISTANCE_NULL_OR_NEGATIVE,
    VEHICLE_RENTING_CUSTOMER_ID_NULL,
    VEHICLE_REGNO_WRONG_LENGTH,
    VEHICLE_MAKE_EMPTY,
    VEHICLE_ODOMETER_NOT_POSITIVE,
    VEHICLE_COSTKM_NOT_POSITIVE,
    VEHICLE_TYPE_NULL,
    VEHICLE_COSTDAY_NOT_POSITIVE,
    VEHICLE_NOT_FOUND,
    CUSTOMER_SSN_NOT_5_DIGITS,
    CUSTOMER_LAST_NAME_EMPTY,
    CUSTOMER_FIRST_NAME_EMPTY,
    CUSTOMER_DUPLICATE_SSN,
    CUSTOMER_NOT_FOUND,
}
